name: Database CI

on:
  push:
    branches:
      - develop
      - 'milestone/**'
  pull_request:
    branches:
      - develop
      - 'milestone/**'

jobs:
  seed:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Wait for MongoDB
        run: |
          echo "Waiting for MongoDB service to initialize..."
          sleep 15

      - name: Install dependencies
        run: |
          npm install

      - name: Run seed script and capture logs
        env:
          MONGODB_URI: mongodb://localhost:27017/tt_cnpm_ci
        continue-on-error: true
        run: |
          mkdir -p ./database
          # run the seed script and capture both stdout and stderr to a log file
          # tee writes to file and also streams to the workflow log
          node database/seed.js 2>&1 | tee ./database/seed.log

      - name: Upload seed logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: database-seed-log
          path: |
            ./database/seed.log
